### ISSUE TITLE
readDouble overflow

### ISSUE THREAD

**Issue by jcalfee** [andrasq/node-ieee-float#1]
```js
// works as expected
> output = [], fp.writeDoubleBE(output, '7199254740993.5'), fp.readDoubleBE(output)
7199254740993.5

// doesn't readDouble need to return a string?
> output = [], fp.writeDoubleBE(output, '9007199254740993.5'), fp.readDoubleBE(output)
9007199254740994

```

**Comment by andrasq** [comment]
readDouble always returns a `number`.  The behavior above is the same with Buffer.readDoubleBE; writeDoubleBE() writes an 8-byte double (not the string), and readDoubleBE() parses a double from the bytes and returns a `number`:
```
$ node -p 'x = new Buffer(40); x.writeDoubleBE("9007199254740993.5"); x.readDoubleBE()'
9007199254740994
```

**Comment by jcalfee** [comment]
JavaScript starts messing up any native number over 53 bits in size.  So I guess the full range of float64 values is not supported here.  Is that your understanding?

**Comment by andrasq** [comment]
yes, but it's not JavaScript, it's float64 itself (ieee-754 64-bit float) that is unable to represent values over 53 bits in magnitude.  9007199254740993.5 (0x20000000000002.8 in hex) requires 55 bits.  The same glitch would happen in other languages too, eg here it is reproduced in C:
```
% cat t.c
#include <stdio.h>
main()
{
    double x = 9007199254740993.5;
    printf("(%30.4f)\n", x);
}
% cc t.c
% a.out
(         9007199254740994.0000)
```

**Comment by larryk85** [comment]
One more thing, I'm not sure if you just had the readDoubleBE for example.  But, you should be using readDoubleLE, the serialized data should be in little endian byte order when you get it. And yes for IEEE 754 double you have 1 sign bit, 11 bits for the exponent and 52 bits for the mantissa or magnitude.  So as to what @andrasq said anything over that will overflow for any system that implements IEEE 754 binary double.
